title:       "Operating Systems 2021-1 (OS211)"
version:     "v1.5"
copyright:   "2021-2021"
description: >- # Multiline
  This site is a journal to record the progress of my OS class at Fasilkom UI.
baseurl: "/os211" # e.g. /blog
url: "https://dnswd.github.io"     # e.g. http://example.com
# google_analytics: "UA-89852122-6"
author:           "dnswd"
address:          "Jakarta"
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://dnswd.github.io/os211/"
urlcontact:       "TBS"
urlgithub:        "https://github.com/dnswd/os211/"
urlghpage:        "https://dnswd.github.io/os211/"
keywords:         "jekyll, testing"
github:           [metadata]
